### ISSUE TITLE
Add concept / mapping in a Collection

### ISSUE THREAD

**Issue by amitendc** [OpenConceptLab/ocl_web#100]
https://github.com/OpenConceptLab/oclapi/wiki/collections#add-concept-reference-to-a-collection

To add individual concept or mapping into a Collection from another Source: 
## Tasks:
1. In the tab (References), display '+ Add New Reference'. This option should appear when Collection Version : 'Head' (Note that this functionality will be implemented as part of #175 )
2. Open a new page with a dynamic text box and 'Add' button.
   ~~3. Search for 'expression' and get search result listing.~~
3. Select ~~(or multi-select)~~ concepts and click on 'Add' to add references of concepts and mappings in the Collection. 
## Result
1. At the time of addition, evaluate if the URL is valid. Throw a error on Duplicate reference or invalid. Blank reference should not be added in Collection. 
2. Show what type of resource does the search expression evaluate to. # of Source, Collections, Concepts and Mappings
3. Add the search expression on the References tab. The references are clickable links to the source.
4. Add the evaluated values of selected concepts and mapping from search result into the Concepts and Mappings tab. (No option to edit/delete/add Concepts and Mappings in the tabs). Allow duplicate concepts and mappings but display unique.
5. Pagination in the Concepts and Mappings page
### Expressions to add individual concepts:
- Latest version of a concept: /orgs/:org/sources/:source/concepts/:concept/
- Concept from a specific source version: /orgs/:org/sources/:source/:sourceVersion/concepts/:concept/
- Specific concept version: /orgs/:org/sources/:source/concepts/:concept/:conceptVersion/
### Expressions to add individual mappings:
- Latest version of a concept: /orgs/:org/sources/:source/mappings/:mapping/
- Concept from a specific source version: /orgs/:org/sources/:source/:sourceVersion/mappings/:mapping/
- Specific concept version: /orgs/:org/sources/:source/concepts/:mapping/:mappingVersion/

![screen shot 2016-08-16 at 11 21 37 am](https://cloud.githubusercontent.com/assets/18673796/17689224/ada9a442-63a3-11e6-9fec-783b24bc408b.png)

![screen shot 2016-08-17 at 11 15 48 am](https://cloud.githubusercontent.com/assets/18673796/17725794/0223d2fe-646c-11e6-9813-5240b8ff20cc.png)

**Comment by AnjaliWadhwa** [comment]
Found below issues which needs fix:
* Reference tab breaks if collections have same name across organisations.
* Under Reference tab, we should see Mapping icon for mapping references.
* Reference to a retired concepts should not be allowed.

**Comment by paynejd** [comment]
Note that references to retired concepts **should** be allowed, although
this would generally be discouraged through the UI.

**Comment by AnjaliWadhwa** [comment]
Some feedback on this story:
* Pagination is not implemented on concept, mappings and references tab.
* After 15 references, app breaks when we click on concepts or mappings tabs.
* In version of a collection, we show concepts ids instead of names. We should show names.
* Under concepts and mappings tab, we are not showing proper structure like /org/source/concept and /org/source/mapping. We missed to show source name in between.
* Error message content should be changed to below texts:
   * Duplicate reference - Reference already exists.
   * Invalid expression - Expression specified is not valid.

**Comment by paynejd** [comment]
A few small pieces of feedback on this (more is coming later after this is complete)...

Permissions:
1. As a user that was not a member of the organization, I saw the "Add Reference" and was able to navigate to the Add Reference page -- I was able to click on the "Add" reference button but then no references were actually added

On Add Multiple References tab:
1. Mappings do not show up at all unless there is at least one concept in the selected repository version
2. Listing of concepts shows the concept version ID not the concept ID -- if the reference being added is actually a concept version, then need to use the proper display for this, e.g. `:owner / :repository / :conceptId [ :conceptVersion ]`
3. Listing of concepts and mappings should allow a user to click through to see the actual details of the mappings/concepts -- the ability to click the entire concept/mapping summary is convenient, but actually is confusing -- I would change these all to links (that open in a new window) and require use of the checkbox

On references listing page:
1. Get rid of the word "collection" in the count of results: e.g. "1-1 out of 1 collection references"

**Comment by paynejd** [comment]
I was able to add a mapping to this collection twice -- is the duplicate checking performed in the UI or the API?

![image](https://cloud.githubusercontent.com/assets/1189689/18654638/bfda716e-7eb0-11e6-8112-5d673117db43.png)

**Comment by AnjaliWadhwa** [comment]
Updates on the feedback above:
* Permissions - We have a separate story for it.
* Add Multiple References tab: this feedback has been moved to #101, fixed and tested.
* On references listing page: This is fixed.
* Add a mapping to this collection twice - we cannot reproduce this issue.
