### ISSUE TITLE
Add all concepts and/or mappings from another source version of current organisation/user into a collection

### ISSUE THREAD

**Issue by amitendc** [OpenConceptLab/ocl_web#101]
See Link - https://github.com/OpenConceptLab/oclapi/wiki/collections#add-a-reference-to-a-collection

NOTE: We will not allow adding concepts/mappings from "HEAD" at this point (and maybe never!)
## Tasks
- Design UI as shown in image below.
- Add new link 'Add multiple References'. Click on this link should show UI as shown in image to add multiple references.
- Either single or multiple reference is mandatory.
- Organization/User (1st field) name should be populated as current org/user collection.
- Source radio button should be selected by default. Populate all the sources from current user/org.
- Populate all the versions from the selected source.
- Once the version is selected, show all the concepts on the left and mapping on the right as shown in the image. 
- Listing should have check box and user should be able to multi select concepts / mappings.
- Click on Add button should add all references of selected concepts and mappings in the references tab of collection. Also evaluated values in respective tabs.
- Implement pagination for concepts and mappings.

![img_4111](https://cloud.githubusercontent.com/assets/3176602/18159181/3a4d356e-7045-11e6-889e-03df5b4c840b.JPG)
### Expressions to add concepts from a source:
- Concept from a specific source version: /orgs/:org/sources/:source/:sourceVersion/concepts/:concept/
- All concepts from specific source version: /orgs/:org/sources/:source/:sourceVersion/concepts/
### Expressions to add mappings from a source:
- Mapping from a specific source version: /orgs/:org/sources/:source/:sourceVersion/mappings/:mapping/
- All mappings from specific source version: /orgs/:org/sources/:source/:sourceVersion/mappings/

**Comment by AnjaliWadhwa** [comment]
This story is further split into 3 more stories #106, #107 and #105

**Comment by AnjaliWadhwa** [comment]
Below is the feedback from Jon:

On Add Multiple References tab:
1. Mappings do not show up at all unless there is at least one concept in the selected repository version - Need to fix.
2. Listing of concepts shows the concept version ID not the concept ID -- if the reference being added is actually a concept version, then need to use the proper display for this, e.g. `:owner / :repository / :conceptId [ :conceptVersion ]` - Need to fix.
3. Listing of concepts and mappings should allow a user to click through to see the actual details of the mappings/concepts -- the ability to click the entire concept/mapping summary is convenient, but actually is confusing -- I would change these all to links (that open in a new window) and require use of the checkbox - Enhancement, will create a separate card for it.

On references listing page:
1. Get rid of the word "collection" in the count of results: e.g. "1-1 out of 1 collection references"

**Comment by AnjaliWadhwa** [comment]
Feedback from story testing:

* If we do not have any version, then it shows all the concepts and mapping as soon as you select source / collection in the 2nd dropdown.
* In concepts tab,  we do not show source name in hierarchy.
* When we change the filter, the results should clear out. 
* Need to work on the warning messages. - this is enhancement and will be done in a separate story later.

**Comment by AnjaliWadhwa** [comment]
All the fix for feedback above looks good.

One more feedback:
* If we have a list of 5 concepts / mapping which we wish to add, out of which 2 already exist, it should show message and add the other 3 concepts / mappings.
