### ISSUE TITLE
Delete a reference from a Collection

### ISSUE THREAD

**Issue by amitendc** [OpenConceptLab/ocl_web#102]
#### Tasks

1. Click on the References tabs view all references.
2. Display '+ Add New Reference' link, a dropdown 'Collection Version: HEAD', text box with 'Search References within', Search icon, Sort By: Dropdown with Options, and Delete button. (Refer to 'Concepts' tabs in Source)
3. Display list of all references. Allow user to filter list by using Search function.
4. Allow user to multi-select references from the search result and 'Delete'.
5. Pop up asking 'Do you want to remove the selected Reference(s) and associated values from Concepts and Mappings tab?'. Options - Yes / No.
6. On selecting any option, close the popup.

### Result
1. On selecting 'Yes', the reference(s) is removed from search result and the evaluated values (Concepts and Mappings) are removed from respective tabs.

## Note: 
1. The Delete option is available only on selecting HEAD.

![screen shot 2016-08-17 at 11 15 48 am](https://cloud.githubusercontent.com/assets/18673796/17725892/ae3ad8f8-646c-11e6-9e6c-f9e8dc357021.png)

**Comment by paynejd** [comment]
this appears to be working as expected!
