### ISSUE TITLE
unicode characters should be supported in search

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_web#103]

**Comment by paynejd** [comment]
This now works as expected in both the global and repository-level search boxes.

**Comment by snyaggarwal** [comment]
This works great with accented characters, but some special characters are still not escaped at Solr query level, ones I know are ----->    : , { , }
This needs character escaping in Solr query, but havent worked on that, as most of the use cases were working in search, with the real-like data.
