### ISSUE TITLE
Search collection for resources within

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#105]
- User should be able to search for concept(s), mapping(s) and reference(s) in the respective tabs under collection and all of its versions.
- Add 'Sort By: Dropdown with Options' same as source. User should be able to sort the search results based on these options.
- Search for partial text should be supported under references tab.

**Comment by AnjaliWadhwa** [comment]
As discussed in BA call, implement sorting in references tab as below:
* By default, search results should be sorted by Created at (Desc).
* Drop down options: 
   * Created at (Asc)
   * Created at (Desc)
   * Name (Asc)
   * Name (Desc)

**Comment by paynejd** [comment]
This is working great. Only thing missing is that references cannot be sorted alphabetically, only by created on timestamp -- is this intentional or is this still being implemented?

**Comment by AnjaliWadhwa** [comment]
This is intentional as References do not have names.
