### ISSUE TITLE
Add all concepts and/or mappings from org/user collection version into a collection 

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#106]
See Link - https://github.com/OpenConceptLab/oclapi/wiki/collections#add-a-reference-to-a-collection

NOTE: We will not allow adding concepts/mappings from "HEAD" at this point (and maybe never!)
## Tasks
- Design UI as shown in image below.
- Organization/User (1st field) name should be populated as org/user collection.
- Source radio button should be selected by default. 
- User should be able to select collection radio button. Populate all the collections from based on previous dropdown selection (user/org) and then populate all the versions from the selected collection.
- Once the version is selected, show all the references of selected collection as shown in the image. 
- Listing should have check box and user should be able to multi select references.
- Click on 'Add' button should add all references in the references tab of collection. Also evaluated values in respective tabs.
- Implement pagination for concepts and mappings.

![img_4112](https://cloud.githubusercontent.com/assets/3176602/18160338/9cbc2f48-704a-11e6-9dfe-709a1148639e.JPG)
### Expressions to add concepts from a collection:
- Concept from a specific collection version: /orgs/:org/collections/:collection/:collectionVersion/concepts/:concept/
- All concepts from specific collection version: /orgs/:org/collections/:collection/:collectionVersion/concepts/
### Expressions to add mappings from a collection:
- Mapping from a specific collection version: /orgs/:org/collections/:collection/:collectionVersion/mappings/:mapping/
- All mappings from specific collection version: /orgs/:org/collections/:collection/:collectionVersion/mappings/

**Comment by paynejd** [comment]
I need more information about how this was implemented in order to test it. Was this integrated into the "Add Multiple References" tab or the "Add Single References" tab? When is a concept/mapping version instead of a concept/mapping head added?

**Comment by AnjaliWadhwa** [comment]
This was integrated into 'Add multiple references' to add concepts/mappings from other collection.
