### ISSUE TITLE
Add collections in global search

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#108]
* User should be able to search collection(s) in global search
    * Show collection in the search list on left side
    * Show 'include retired' checkbox on the left for collections (same as concepts)
* Unicode characters in collection names should be searchable.

**Comment by AnjaliWadhwa** [comment]
Feedback:
* User should be able to search with short_code.

**Comment by paynejd** [comment]
Search can rely on the ID instead of short_code, since short_code will be
retired.

**Comment by derektreatman** [comment]
Unable to add new collection with unicode name for testing, tried with collection name "ሌላ" here: http://staging.openconceptlab.org/orgs/EthiopiaMOH/collections/new/. Get error message that simply states "Error".

**Comment by paynejd** [comment]
This appears to be working correctly!
