### ISSUE TITLE
'latest' magic keyword should return latest released version

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#109]
* User should get latest released version of source / collection by using "latest" keyword.
* Currently it breaks if we have multiple release versions. In such case it should return the latest one.
* ~~User should be able to export the latest version by this keyword~~. 
* If there are no released versions, 
    * then on UI '/latest' should throw error 'There are no released versions'.
    * In export, show '404 Not Found'.
* This should work for both under User and Org.

**Expressions:**

**For Source**
```
GET /user/sources/:source/latest/
GET /users/:user/sources/:source/latest/
GET /orgs/:org/sources/:source/latest/ 
```

**For Collection**
```
GET /user/collections/:collection/latest/
GET /users/:user/collections/:collection/latest/
GET /orgs/:org/collections/:collection/latest/
```

**Comment by AnjaliWadhwa** [comment]
This works fine for Org / user source but fails for Collection. Need to fix it.

**Comment by paynejd** [comment]
Tested for sources and collections and works exactly as expected.

**Comment by paynejd** [comment]
Retired repository versions should not be returned by the "latest" keyword.

Take a look here: http://showcase.openconceptlab.org/orgs/PayneOrg/sources/PayneSource/versions/

v1.9 is retired and released
v1.8 is released

"latest" should return v1.8, because v1.9 is retired

**Comment by AnjaliWadhwa** [comment]
Feedback from showcase - Show latest released version id on UI instead of [latest] keyword.

**Comment by mKadiyan** [comment]
Released and retire handling with 'latest' handled.

**Comment by AnjaliWadhwa** [comment]
Feedback is fixed and working fine now.

**Comment by paynejd** [comment]
Working as expected!
