### ISSUE TITLE
[Bug] Edit of mapping under user source

### ISSUE THREAD

**Issue by AnshuAg** [OpenConceptLab/ocl_web#110]

**Comment by paynejd** [comment]
This works even better than expected! Not only was editing of mappings under a user source allowed, but I was also able to see the early implementation of mapping versions, which appear to be _almost_ working (the mapping was not tracked correctly in the source versions...)

**Comment by AnjaliWadhwa** [comment]
Mapping under source / collection version tracking is being implemented in https://github.com/OpenConceptLab/oclapi/issues/213
