### ISSUE TITLE
Mappings showed up under new empty source!

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_web#111]
I just created a new source on showcase:

http://showcase.openconceptlab.org/users/paynejd/sources/JonsSource/

I navigated to the "Mappings" tab and 6 mappings showed up that were part of different sources!

![image](https://cloud.githubusercontent.com/assets/1189689/18653567/b9efdf26-7ea8-11e6-85a3-2f9edf443a31.png)

**Comment by AnjaliWadhwa** [comment]
This issue is fixed and it seems to be working fine now.

**Comment by paynejd** [comment]
Tested and this is fixed.
