### ISSUE TITLE
HEAD repository versions should not be editable

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_web#112]
The HEAD version of a repository should not be editable. Currently, it allows you to edit the description, but we should prevent editing of the HEAD entirely. See below for example:

![image](https://cloud.githubusercontent.com/assets/1189689/18653782/3daeb9bc-7eaa-11e6-9bab-ca12445df0b9.png)

![image](https://cloud.githubusercontent.com/assets/1189689/18653795/61caf036-7eaa-11e6-8328-85dcb99744a0.png)

**Comment by AnjaliWadhwa** [comment]
This is fixed.

**Comment by paynejd** [comment]
Tested and this looks good!
