### ISSUE TITLE
Error handling on UI

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#120]
Some errors throw exceptions rather than being handled by the UI. Here's the list of one's that need to be addressed:

@paynejd to update the list
- Source version with same name
- Collection version with same name
- Adding a non-existent user as a member of Org - no error message comes up
- Retire internal or external mappings. Created #131 for it
- Create Org with some special characters. This is done in https://github.com/OpenConceptLab/oclapi/issues/226

**Comment by mKadiyan** [comment]
Need to add proper error messages for 
* User / Org Source already exists error
   * Source with short code 'code' already exists.
* User / Org Collection already exists error
   * Collection with short code 'code' already exists.

**Comment by AnjaliWadhwa** [comment]
Error messages listed in this card are working fine now. Screenshot below:

* Source version same name

<img width="1280" alt="screen shot 2016-10-05 at 16 57 15" src="https://cloud.githubusercontent.com/assets/3176602/19113524/ab2c2c66-8b27-11e6-9d98-2a53d71ea684.png">

* Collection version same name

<img width="1280" alt="screen shot 2016-10-05 at 16 58 00" src="https://cloud.githubusercontent.com/assets/3176602/19113525/ab2d6b6c-8b27-11e6-95db-f9a52f40f3f7.png">

* Add invalid user as a member of org

<img width="1440" alt="screen shot 2016-10-05 at 6 14 40 pm" src="https://cloud.githubusercontent.com/assets/3176602/19113546/d4b62a46-8b27-11e6-8705-5509ab6d09c5.png">

* Collection with same name. Same is for Source also.

<img width="1440" alt="screen shot 2016-10-05 at 6 14 20 pm" src="https://cloud.githubusercontent.com/assets/3176602/19113547/d641223a-8b27-11e6-99f1-da4cd14b5461.png">
