### ISSUE TITLE
Must not be able to have an empty concept description

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#121]
Must not be able to have an empty concept description 

Example: http://showcase.openconceptlab.org/users/paynejd/sources/JonsSource/concepts/ultra-sticky/?debug=1

**Comment by paynejd** [comment]
Note that descriptions are not required, but if one is saved it must not be
empty

**Comment by AnjaliWadhwa** [comment]
This is fixed and working fine now.

**Comment by AnshuAg** [comment]
When a users create a new concept and not added description then description and description field should not appear when debug=1 in url.
