### ISSUE TITLE
Inconsistent concept search results

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#124]
Some concepts are showing up in the global search but not in the search for either the source or collection. However, they are showing up at the repository level if no search criteria are provided and showing up in the references for collections. It appears that this is due to the way the names are being indexed. Note that the names in question were somewhat funky (e.g. "lgtest.dd.70"). Ideally, we want to improve the index so that a user would be able to see the above concept by searching for "lgtest". At a minimum, I need a description on how the index is constructed so that we can describe the behavior to users in the user documentation so that no one is surprised.

See: http://staging.openconceptlab.org/users/leahgatt/sources/CIEL/concepts/?q=LGTEST&sort=Best+Match

http://staging.openconceptlab.org/users/leahgatt/collections/testing/concepts/?q=LGTEST&sort=Best+Match

http://staging.openconceptlab.org/search/?q=LGTEST

**Comment by paynejd** [comment]
Your suggested approach got the green light! Automatically adding an asterisk to the search criteria by default and removing the asterisk when the "Exact match" checkbox is checked.

**Comment by snyaggarwal** [comment]
Cool!
@AnjaliWadhwa or @paynejd -- can someone please create a card.

**Comment by paynejd** [comment]
Closing this card and created new card #133 for the solution to this.
