### ISSUE TITLE
Add asterisk to end of search criteria by default unless "exact match" is checked

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_web#133]
As discussed, this will fix situations where a partial search term is unable to match with a full phrase. E.g. q=lgtest does not match "lgtest.a.5", but "lgtest*" does.

Assuming that this will only affect the UI, and that no change will be made in the API.

**Comment by paynejd** [comment]
For reference, here is the original issue that was described:

Some concepts are showing up in the global search but not in the search for either the source or collection. However, they are showing up at the repository level if no search criteria are provided and showing up in the references for collections. It appears that this is due to the way the names are being indexed. Note that the names in question were somewhat funky (e.g. "lgtest.dd.70"). Ideally, we want to improve the index so that a user would be able to see the above concept by searching for "lgtest". At a minimum, I need a description on how the index is constructed so that we can describe the behavior to users in the user documentation so that no one is surprised.

See: http://staging.openconceptlab.org/users/leahgatt/sources/CIEL/concepts/?q=LGTEST&sort=Best+Match

http://staging.openconceptlab.org/users/leahgatt/collections/testing/concepts/?q=LGTEST&sort=Best+Match

http://staging.openconceptlab.org/search/?q=LGTEST

**Comment by AnjaliWadhwa** [comment]
Testing of this is complete. Functionality wise it is working fine, however, there are some UI related alignment issues which we need to fix.
