### ISSUE TITLE
'active_concepts' and 'active_mappings' should include resources where 'retired=false' and 'is_active=true'

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#134]
For all versions we need to calculate 'active_concepts' and 'active_mappings' and it should include resources where **_'retired=false'_ and _'is_active=true'_.** 

Currently it takes resources where 'is_active=true' because of which we get count of retired resources as well.

Note that value of these fields should be captured every time we create Source / Collection version and freeze it like version itself.

**Comment by AnjaliWadhwa** [comment]
This is working fine for 'active_concepts'. Need to check this logic for 'active_mappings' after #131

**Comment by paynejd** [comment]
There is still an issue in which active counts do not match the underlying number of active resources, however it is due to a different issue. Closing this ticket and creating a new one
