### ISSUE TITLE
Data synchronization between API and Web breaks when Web fails

### ISSUE THREAD

**Issue by cengizIO** [OpenConceptLab/ocl_web#136]
Hello

While we were working on the codebase, we discovered this serious unhandled condition which can be reproduced like this:
1. Do some operation on web side, eg: Sign-up with new user
2. Receive an exception on web app during operation, due to misconfiguration or alike
3. API now has user info persisted, but web doesn't know anything about it.

After this, you can't submit the form for that user info anymore. You have to clear API manually and restart the flow.

Is there a transaction mechanism? Maybe we're missing it.

We were using SQLite on web by the way.

Thanks

**Comment by cengizIO** [comment]
@ayseyo this is the bug we discovered together

**Comment by paynejd** [comment]
Thanks for creating a ticket for this -- I've experienced this error as well. Keeping this as high priority.
