### ISSUE TITLE
Verification and reset password emails needs improvement

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#147]
- Email should be sent from simply "noreply@openconceptlab.org" -- note the .org not .com! Currently we are sending it from ocl_web ocl_web_noreply@openconceptlab.com
- Production email verification and reset password is still going to spam -- any way we can fix this?

**Comment by AnjaliWadhwa** [comment]
This is fixed. Email is now coming from 'noreply@openconceptlab.org' and it seems to land in Inbox properly. Let's check it on Staging and Prod once we deploy the code there.

**Comment by paynejd** [comment]
Emails still go to spam. This will likely be resolved when switching to the new server environment and shifting to a real email account hosted on the OCL google suites account, so closing for now.
