### ISSUE TITLE
Feedback on 'exact_match' implementation

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#148]
Below examples are from prod - https://openconceptlab.org/
- "diabetes" resulted in zero concepts -- but it  showed 100+ results when exact match was clicked -- this is an error in exact match implementation
- "snomed" and "snomed-ct" have zero results but there are 4 results when exact match is clicked -- this is also an error in exact match implementation
- "Exact match" selection is not retained when clicking between resource types -- e.g. select "Exact match" and search for "snomed", which will show zero concepts, then click on sources
- Global search criteria is being passed between pages incorrectly -- e.g. "malaria" search, then switch to mappings and it shows up as "*malaria*" in the search box

**Comment by paynejd** [comment]
Another example of "exact_match" not working as expected:
* Do a global search for "locales": http://showcase.openconceptlab.org/search/?q=locales
    * Note that there are zero concept results and 1 result for sources shown at left
* Now, select the "Sources" link, which should give you 1 result: http://showcase.openconceptlab.org/search/?type=sources&q=locales
    * Instead, there are zero results for sources and now there is 1 concept result shown at left!
* Now, select "exact match" and re-submit the sources search: http://showcase.openconceptlab.org/search/?type=sources&exact_match=on&q=locales
    * Now we see the one search result
* Now, select the "Concepts" link to find out what the 1 search result is
    * Note that "exact_match" is not carried over, so we lose the search result -- so, go ahead and select exact_match and re-submit to find that we do have one concept result with "Locale" in it

**Comment by AnjaliWadhwa** [comment]
This is fixed and seem to work fine on showcase.

**Comment by paynejd** [comment]
"exact_match" on searches within repositories incorrectly adds asterisks around the search criteria in the form field. For example, a user searches for "malaria" and clicks on submit. The search box now says "*malaria*"
