### ISSUE TITLE
Unable to remove a member from an organization

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/ocl_web#152]
<img width="1280" alt="screen shot 2016-10-20 at 13 09 12" src="https://cloud.githubusercontent.com/assets/3176602/19550317/93c169ce-96c6-11e6-8d04-2421037f040d.png">

**Comment by AnjaliWadhwa** [comment]
Feedback:
* Owners of org should not be able to delete themselves.

**Comment by paynejd** [comment]
Confirmed that this is still not working
