### ISSUE TITLE
username allowable char set: words and underscore for app, but signup screen allows others

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/ocl_web#20]
Need to sync up signup screen username character rules with the rest of the application. Otherwise user can generate a username that fails in other URL's like user profile page.

For example, username with "@" (email) in the username does not work.

Background:
The API accepts URL with this pattern: [a-zA-Z0-9\-\.]+
note that underscore character is not allowed.

Signup form/web:
Currently the signup form allows for underscore.

**Comment by paynejd** [comment]
Is this complete? Either close if complete or provide an update.

**Comment by pkshiu** [comment]
Modified signup screen on website to only allow alphanumeric plus dot and dash.
