### ISSUE TITLE
UI to edit "retired" attribute of concept

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/ocl_web#23]
Note that "retiring" a concept is done using the DELETE API call.

User should be prompted to enter the reason for retiring the concept (this can be sent with the DELETE API call and is saved with the newly created concept version).

**Comment by pkshiu** [comment]
The "trashcan icon" on edit is the retire button.

**Comment by paynejd** [comment]
Jon will modify the UI to make it clear this is a "retire" and not delete.
