### ISSUE TITLE
locales are stored as codes, but other types are stored as names

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/ocl_web#26]
This should be given some though in the future:

In the database locales are stored using their codes (e.g. en, fr etc) and the users are expected to know this. Whereas for other value list type attributes like datatypes, concept classes are stored just using their names (boolean, anatomy etc).

So the program source handles them differently while they are used in the same way in filtering searches etc. It would be nice if all this are normalized somehow so that locale does not have to be treated differently.

The program source files effected are:
- libs/ocl/search.py which create the HTML filters for searches
- project.js which handle angularJS forms dropdown fields for entering and editing these fields
- core/views.py which serves these lists to project.js via json views, and also currently hard code the list of values.

**Comment by paynejd** [comment]
In the future, in any place where locales are used, users should be able to use the fully specified name (e.g. English) or the code (e.g. "en"). Locales should always be saved and/or sent to the API using codes. The display for locales should always show both (e.g. "English [en]").
