### ISSUE TITLE
Nav bar:  if it can't fit, use Bootstrap to reduce the menu into a dynamic menu

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/ocl_web#27]
Really only useful for mobile/phone access?

**Comment by paynejd** [comment]
Even on my laptop screen, the nav bar only fits onto a single line if I
have my browser window on the full screen - anything more narrow than that
and it moves to two lines.

--
Jonathan Payne, MS
615.579.5413
skype: jonathandavidpayne

**Comment by paynejd** [comment]
PK updated this to keep the nav menu and global search bar on one line unless the screen is very narrow (i.e. mobile). In the next milestone, update the styling so that the narrow display still looks ok (e.g. condense the menu into a dynamic dropdown).
