### ISSUE TITLE
"Add Concept" page layout is different from "Add Source" 

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/ocl_web#36]
Add Source and Add Org uses vertical forms, while "add concept" uses horizontal form.

I think we actually have more vertical forms then horizontal, so we should move the concept ones to vertical instead.

**Comment by paynejd** [comment]
sounds good to me! just want to be consistent.

--
Jonathan Payne, MS
615.579.5413
skype: jonathandavidpayne
