### ISSUE TITLE
Empty search of sources result counts are wrong, possibly because of retired_concept bug

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/ocl_web#46]
On an "empty search" of sources (http://staging.openconceptlab.org/search/?type=sources), if you add up the number of concepts in all the sources in the source results, it is significantly smaller than the number of concepts indicated in the top-left nav box (52715 vs. 48959) -- which is correct? Is the concept count field in the sources not being updated or is there another problem?

Possibly related to retired_concepts are returned incorrectly.

**Comment by paynejd** [comment]
Appears to be fixedd
