### ISSUE TITLE
Fix concept history "updated_by" display

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/ocl_web#49]
See: http://dev.openconceptlab.org/orgs/OMRS/sources/OMRS/concepts/1826/

![image](https://cloud.githubusercontent.com/assets/1189689/6159533/b8311224-b224-11e4-8655-65a525598de7.png)

(Jon messed this up -- tried to use django syntax when it should have been angular syntax)

**Comment by paynejd** [comment]
fixed!
