### ISSUE TITLE
Need ability to edit membership of an organization

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_web#65]
Currently there is no way to edit the membership of an organization. If a user has editing privileges for an org, add a link to "Add member" and add a link to remove members.

**Comment by pkshiu** [comment]
Implemented. Although could use a way to really check for admin access to do the adding.

**Comment by paynejd** [comment]
Hi PK, right now there are no real "permissions" for users, just membership.

Aaron, can all members of an organization add/remove or only the "creator"
of the organization?

--
Jonathan Payne, MS
615.579.5413
*LinkedIn:* www.linkedin.com/in/jonathandavidpayne
*Skype:* jonathandavidpayne
