### ISSUE TITLE
Fix error handling for new org with invalid short code

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_web#72]
Currently shows a nasty error message - note that org short code was invalid. It works fine if the short code is valid.

![image](https://cloud.githubusercontent.com/assets/1189689/6088381/bedd3314-ae23-11e4-947c-98f039e4d3d2.png)

**Comment by AnjaliWadhwa** [comment]
This has been fixed in https://github.com/OpenConceptLab/oclapi/issues/226
