### ISSUE TITLE
Implement "external_id" field in concepts, names, descriptions, mappings, sources, and collections

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_web#74]
We used an extra called "external_id" to store the OpenMRS concept UUID upon import. A field called "external_id" will be added as a core attribute to concepts, names, descriptions, mappings, sources and collections during this round of API edits. This field should be added to the web application objects, to the CRUD pages for these objects, and of course to the import script.

Refer to the API wiki for details of where "external_id" attribute has been added.

**Comment by pkshiu** [comment]
This is done except collections and mappings. I am splitting that up into a separate ticket.
