### ISSUE TITLE
"public_access" field is returned with org details

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_web#76]
The "public_access" field is somehow returned with the org details, even though this is an attribute of "sources" and "collections", not "orgs".

Is this field being used to control public permissions at the org level? Or is this a bug?

```
http://api.dev.openconceptlab.com/v1/orgs/OMRS/
```
![image](https://cloud.githubusercontent.com/assets/1189689/6206900/6694b344-b562-11e4-8b75-2aa341fdc2a4.png)

**Comment by MisterNando** [comment]
@paynejd , I thought this had to do with the ability to view/edit org details/members.
