### ISSUE TITLE
Sort on Global Search is incorrect

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_web#77]
Sort on global search is not actually working correctly:
* Name (asc / desc) are both sorting by the concept ID
* Best Match is no different than Last Update (desc) - it is supposed to be a relevancy sort

Are these issues in the Web app or API?

**Comment by pkshiu** [comment]
I think this is the API. I just specify the sort key as "last_update" or "name" in the call.

**Comment by paynejd** [comment]
Hi Aaron, it appears that sorting is not working correctly for concepts. If no sort is set, it is supposed to do a "relevancy" search, but instead is sorting by Last Update (desc). Name asc/desc are both sorting by concept ID instead of the display name.

**Comment by paynejd** [comment]
Please refer to the "Proposed Search and Filter Behavior" section of each resource for the expected sorting behavior. It appears that the "Best Match" filtering was not implemented for any resources when I had assumed, without specifying it, that this would be the default behavior for most lists.

**Comment by pkshiu** [comment]
@paynejd @MisterNando should this be moved to the API side?

**Comment by MisterNando** [comment]
Makes sense to me.

**Comment by paynejd** [comment]
This has been fixed.
