### ISSUE TITLE
External ID not populated for concept names

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_web#85]
See CIEL:123 (http://www.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/123/?debug=true)

![image](https://cloud.githubusercontent.com/assets/1189689/7088973/4fb0f4b6-df66-11e4-9f14-a3d7a757486e.png)

**Comment by pkshiu** [comment]
This is fixed and will take effect next time we import concepts. Currently first 100 or so concepts were reimported to test this on dev.
