### ISSUE TITLE
Retired field not imported correctly?

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_web#86]
CIEL:123 Malaria is a retired concepts.

See on MCL: http://www.maternalconceptlab.com/search.php?q=id:123&source=openmrs

It is not retired on OCL - take a look here: 
* Concept details: http://www.openconceptlab.com/orgs/CIEL/sources/CIEL/concepts/123/?debug=true
* Search results page: http://www.openconceptlab.com/search/?q=123&debug=true

Is this an issue with the import?

**Comment by pkshiu** [comment]
The retired flag currently is not being processed by the import because the creation API does not support importing retired concept directly. i.e. We have to retire them after import.

I am writing a quick utility to do this after the initial import.

**Comment by paynejd** [comment]
This is a high priority fix then.

**Comment by paynejd** [comment]
This has been fixed by PK's retirement script.
