### ISSUE TITLE
new org creation not working.

### ISSUE THREAD

**Issue by mKadiyan** [OpenConceptLab/ocl_web#95]
creation of new organisation from web not working. error says , "invalid form" and log file says "name" is missing

**Comment by mKadiyan** [comment]
- Org model value 'name' was not mapped with the full name of organisation. By mapping the full name with name model solved the problem

**Comment by AnjaliWadhwa** [comment]
Tested this bug on showcase env. I can now create a new Org

**Comment by paynejd** [comment]
Testing complete - this is working as expected.
