### ISSUE TITLE
Implement Edit and Delete Operation for a Collection.

### ISSUE THREAD

**Issue by mKadiyan** [OpenConceptLab/ocl_web#97]
- User should be able to edit the existing collection
- User should be able to delete a collection (delete from database)

**Comment by amitendc** [comment]
Retire and Delete is part of scope of #170

**Comment by paynejd** [comment]
#170 refers to retiring/deleting collection versions, NOT to retiring/deleting collections themselves. Users can "deactivate" a collection with a `DELETE` request. "Retiring" of collections is not part of the specification.

**Comment by paynejd** [comment]
This works as expected
